package Project1;

import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;

/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * File                 QuiltGUI.java
 * Description:         This class provides the GUI for buying quilts. This
 *                      GUI HW is intended for an online store that sells
 *                      handmade high quality quilts.
 *                      
 * 
 * History              Log Updated from 4/23/2023
 * Project              Gina's Quilt Works
 * Environment           JDK 1.0.0_241; NetBeans IDE 17.0, MAC OS Monterey
 * Course               CS 141 ON1, Spring 2023, Edmonds
 * Date:                April 23, 2023
 * Due Date:            April 25th, 2023 11:59 PM
 * @author               <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 javax.swing.JFrame
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

public class QuiltGUI extends javax.swing.JFrame {
    
 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Constructor          Default Constructor
 * Description:         Creates the form as designed, centers it, sets the icon
 *                      calculateJButton as default, display current date in 
 *                      title, set background color.
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 java.text.DateFormat
 * @see                 java.text.SimpleDateFormat
 * @see                 java.util.Date
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
  
    public QuiltGUI() {
       initComponents();  //create the form
        
       // set calculate J button as defualt
       this.getRootPane().setDefaultButton(calculateJButton);
       //set icon
       //MACbook does not have icons
       //this.setIconImage(Toolkit.getDefaultToolkit().getImage("/src/Project1/titleImage.jpg"));
       //center form at start
       this.setLocationRelativeTo(null);
       this.getContentPane().setBackground(new Color(11, 143, 177));
       
       //make JSpinners read only ( not editable)
       ((JSpinner.DefaultEditor) quantityHighJSpinner.getEditor()).getTextField().setEditable(false);
       ((JSpinner.DefaultEditor) quantityMediumJSpinner.getEditor()).getTextField().setEditable(false);
       ((JSpinner.DefaultEditor) quantityLowJSpinner.getEditor()).getTextField().setEditable(false);
       //set date to current system date
       setDate();

    }
    
 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * method               setDate
 * Description:         Set a format string for current date, and display it in 
 *                      the respective text field
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 java.text.DateFormat
 * @see                 java.text.SimpleDateFormat
 * @see                 java.util.Date
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void setDate() {
        //date format string
        DateFormat dateFormat = new SimpleDateFormat("MM/dd/yyyy");
        Date date = new Date(); // get current date and time

        // format the date as a string
        String dateString = dateFormat.format(date);

        // set the text of the JFormattedTextField to the formatted date string
        dateJFormattedTextField.setText(dateString);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exampleJPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jFrame1 = new javax.swing.JFrame();
        jSpinner1 = new javax.swing.JSpinner();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        customerInfoJPanel = new javax.swing.JPanel();
        invoiceNumberJFormattedTextField = new javax.swing.JFormattedTextField();
        dateJFormattedTextField = new javax.swing.JFormattedTextField();
        customerJFormattedTextField = new javax.swing.JFormattedTextField();
        invoiceJLabel = new javax.swing.JLabel();
        dateJLabel = new javax.swing.JLabel();
        customerJLabel = new javax.swing.JLabel();
        quiltsJPanel = new javax.swing.JPanel();
        quiltTItleJLabel = new javax.swing.JLabel();
        quiltQuantityJLabel = new javax.swing.JLabel();
        highQuiltJLabel = new javax.swing.JLabel();
        quantityHighJSpinner = new javax.swing.JSpinner();
        mediumQuiltJLabel = new javax.swing.JLabel();
        quantityMediumJSpinner = new javax.swing.JSpinner();
        lowQuiltJLabel = new javax.swing.JLabel();
        quantityLowJSpinner = new javax.swing.JSpinner();
        customerPricingJPanel = new javax.swing.JPanel();
        quiltPriceJLabel = new javax.swing.JLabel();
        extendedPriceJLabel = new javax.swing.JLabel();
        highPriceJLabel = new javax.swing.JLabel();
        extendedHighJLabel = new javax.swing.JLabel();
        mediumPriceJLabel = new javax.swing.JLabel();
        extendedMediumJLabel = new javax.swing.JLabel();
        lowPriceJLabel = new javax.swing.JLabel();
        extendedLowJLabel = new javax.swing.JLabel();
        buttonsJPanel = new javax.swing.JPanel();
        calculateJButton = new javax.swing.JButton();
        clearJButton = new javax.swing.JButton();
        quitJButton = new javax.swing.JButton();
        priceJPanel = new javax.swing.JPanel();
        subTotalJLabel = new javax.swing.JLabel();
        subTotalPriceJLabel = new javax.swing.JLabel();
        customerTaxJLabel = new javax.swing.JLabel();
        taxTotalJLabel = new javax.swing.JLabel();
        quiltAndTaxPriceJLabel = new javax.swing.JLabel();
        totalPriceJLabel = new javax.swing.JLabel();
        titleJPanel = new javax.swing.JPanel();
        titleJLabel = new javax.swing.JLabel();
        quiltJMenuBar = new javax.swing.JMenuBar();
        quitJMenu = new javax.swing.JMenu();
        clearJMenuItem = new javax.swing.JMenuItem();
        printJMenuItem = new javax.swing.JMenuItem();
        quitJMenuItem = new javax.swing.JMenuItem();
        helpJMenu = new javax.swing.JMenu();
        aboutJMenuItem = new javax.swing.JMenuItem();

        exampleJPanel.setBackground(new java.awt.Color(186, 143, 177));
        exampleJPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Parcel Information"));

        javax.swing.GroupLayout exampleJPanelLayout = new javax.swing.GroupLayout(exampleJPanel);
        exampleJPanel.setLayout(exampleJPanelLayout);
        exampleJPanelLayout.setHorizontalGroup(
            exampleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 65, Short.MAX_VALUE)
        );
        exampleJPanelLayout.setVerticalGroup(
            exampleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Project 1--Quilt Application");
        setResizable(false);

        customerInfoJPanel.setBackground(new java.awt.Color(11, 143, 177));
        customerInfoJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        try {
            invoiceNumberJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        invoiceNumberJFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        invoiceNumberJFormattedTextField.setToolTipText("Enter your 4 digit invoice number");

        dateJFormattedTextField.setEditable(false);
        dateJFormattedTextField.setToolTipText("Today's date");
        dateJFormattedTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateJFormattedTextFieldActionPerformed(evt);
            }
        });

        try {
            customerJFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("******************************")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        customerJFormattedTextField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        customerJFormattedTextField.setToolTipText("Type your name please.");

        invoiceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        invoiceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        invoiceJLabel.setText("Invoice number:");

        dateJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        dateJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dateJLabel.setText("Date:");
        dateJLabel.setToolTipText("");

        customerJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        customerJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerJLabel.setText("Customer name:");

        javax.swing.GroupLayout customerInfoJPanelLayout = new javax.swing.GroupLayout(customerInfoJPanel);
        customerInfoJPanel.setLayout(customerInfoJPanelLayout);
        customerInfoJPanelLayout.setHorizontalGroup(
            customerInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, customerInfoJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(customerInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(customerInfoJPanelLayout.createSequentialGroup()
                        .addComponent(invoiceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(invoiceNumberJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(dateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(customerInfoJPanelLayout.createSequentialGroup()
                        .addComponent(customerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customerJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        customerInfoJPanelLayout.setVerticalGroup(
            customerInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(customerInfoJPanelLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(customerInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invoiceJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(invoiceNumberJFormattedTextField)
                    .addComponent(dateJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(customerInfoJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(customerJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerJFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        quiltsJPanel.setBackground(new java.awt.Color(11, 143, 177));
        quiltsJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        quiltsJPanel.setLayout(new java.awt.GridLayout(4, 2, 5, 5));

        quiltTItleJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quiltTItleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quiltTItleJLabel.setText("Quilt");
        quiltTItleJLabel.setToolTipText("");
        quiltsJPanel.add(quiltTItleJLabel);

        quiltQuantityJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quiltQuantityJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quiltQuantityJLabel.setText("Quantiy");
        quiltQuantityJLabel.setToolTipText("");
        quiltsJPanel.add(quiltQuantityJLabel);

        highQuiltJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        highQuiltJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/highQuilt.jpeg"))); // NOI18N
        highQuiltJLabel.setToolTipText("Name: HIgh Quilt, Price: $950, Quanity: 6");
        highQuiltJLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        quiltsJPanel.add(highQuiltJLabel);

        quantityHighJSpinner.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quantityHighJSpinner.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)6), Byte.valueOf((byte)1)));
        quantityHighJSpinner.setToolTipText("6 quilts left");
        quiltsJPanel.add(quantityHighJSpinner);

        mediumQuiltJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mediumQuiltJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/mediumQuilt.jpeg"))); // NOI18N
        mediumQuiltJLabel.setToolTipText("Name:Medium Quilt, Price: $480, Quantity: 10");
        quiltsJPanel.add(mediumQuiltJLabel);

        quantityMediumJSpinner.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quantityMediumJSpinner.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)10), Byte.valueOf((byte)1)));
        quantityMediumJSpinner.setToolTipText("10 quilts left");
        quiltsJPanel.add(quantityMediumJSpinner);

        lowQuiltJLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lowQuiltJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/lowQuilt.jpeg"))); // NOI18N
        lowQuiltJLabel.setToolTipText("Name: Low Quilt, Price: $ 315, quanity: 3");
        quiltsJPanel.add(lowQuiltJLabel);

        quantityLowJSpinner.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quantityLowJSpinner.setModel(new javax.swing.SpinnerNumberModel(Byte.valueOf((byte)0), Byte.valueOf((byte)0), Byte.valueOf((byte)3), Byte.valueOf((byte)1)));
        quantityLowJSpinner.setToolTipText("3 quilts left");
        quiltsJPanel.add(quantityLowJSpinner);

        customerPricingJPanel.setBackground(new java.awt.Color(11, 143, 177));
        customerPricingJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        customerPricingJPanel.setLayout(new java.awt.GridLayout(4, 2));

        quiltPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quiltPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        quiltPriceJLabel.setText("Price");
        quiltPriceJLabel.setToolTipText("");
        customerPricingJPanel.add(quiltPriceJLabel);

        extendedPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        extendedPriceJLabel.setText("Extended Price");
        extendedPriceJLabel.setToolTipText("");
        customerPricingJPanel.add(extendedPriceJLabel);

        highPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        highPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        highPriceJLabel.setText("$950.00");
        customerPricingJPanel.add(highPriceJLabel);

        extendedHighJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        extendedHighJLabel.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        extendedHighJLabel.setToolTipText("");
        customerPricingJPanel.add(extendedHighJLabel);

        mediumPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        mediumPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mediumPriceJLabel.setText("$480.00");
        customerPricingJPanel.add(mediumPriceJLabel);

        extendedMediumJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        extendedMediumJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        extendedMediumJLabel.setToolTipText("");
        customerPricingJPanel.add(extendedMediumJLabel);

        lowPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        lowPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lowPriceJLabel.setText("$315.00");
        customerPricingJPanel.add(lowPriceJLabel);

        extendedLowJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        extendedLowJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        extendedLowJLabel.setToolTipText("");
        customerPricingJPanel.add(extendedLowJLabel);

        buttonsJPanel.setBackground(new java.awt.Color(11, 143, 177));
        buttonsJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        calculateJButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        calculateJButton.setMnemonic('C');
        calculateJButton.setText("Calculate");
        calculateJButton.setToolTipText("Be sure to include Invoice number, your name, and at least 1 quilt to buy before pressing");
        calculateJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateJButtonActionPerformed(evt);
            }
        });

        clearJButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        clearJButton.setMnemonic('R');
        clearJButton.setText("Clear");
        clearJButton.setToolTipText("Clears input fields as well as costs generated");
        clearJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJButtonActionPerformed(evt);
            }
        });

        quitJButton.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quitJButton.setMnemonic('Q');
        quitJButton.setText("Quit");
        quitJButton.setToolTipText("Quits the application");
        quitJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonsJPanelLayout = new javax.swing.GroupLayout(buttonsJPanel);
        buttonsJPanel.setLayout(buttonsJPanelLayout);
        buttonsJPanelLayout.setHorizontalGroup(
            buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsJPanelLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(calculateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        buttonsJPanelLayout.setVerticalGroup(
            buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonsJPanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(buttonsJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(calculateJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        priceJPanel.setBackground(new java.awt.Color(11, 143, 177));
        priceJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        priceJPanel.setLayout(new java.awt.GridLayout(3, 2));

        subTotalJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        subTotalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        subTotalJLabel.setText("SubTotal:");
        priceJPanel.add(subTotalJLabel);

        subTotalPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        subTotalPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subTotalPriceJLabel.setToolTipText("Total price of all quilts, does not include tax");
        priceJPanel.add(subTotalPriceJLabel);

        customerTaxJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        customerTaxJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        customerTaxJLabel.setText("Tax:");
        priceJPanel.add(customerTaxJLabel);

        taxTotalJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        taxTotalJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        taxTotalJLabel.setText(" ");
        taxTotalJLabel.setToolTipText("The total amount of tax you will pay");
        priceJPanel.add(taxTotalJLabel);

        quiltAndTaxPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        quiltAndTaxPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        quiltAndTaxPriceJLabel.setText("Total:");
        priceJPanel.add(quiltAndTaxPriceJLabel);

        totalPriceJLabel.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        totalPriceJLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalPriceJLabel.setToolTipText("Tax plus sub total");
        priceJPanel.add(totalPriceJLabel);

        titleJPanel.setBackground(new java.awt.Color(11, 143, 177));
        titleJPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        titleJLabel.setBackground(new java.awt.Color(11, 143, 177));
        titleJLabel.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        titleJLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        titleJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project1/titleImage.jpeg"))); // NOI18N
        titleJLabel.setText("Gini's Quilt Works");
        titleJLabel.setToolTipText("Welcome to our site!");

        javax.swing.GroupLayout titleJPanelLayout = new javax.swing.GroupLayout(titleJPanel);
        titleJPanel.setLayout(titleJPanelLayout);
        titleJPanelLayout.setHorizontalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titleJPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(titleJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        titleJPanelLayout.setVerticalGroup(
            titleJPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleJLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        quitJMenu.setMnemonic('F');
        quitJMenu.setText("File");

        clearJMenuItem.setMnemonic('r');
        clearJMenuItem.setText("Clear");
        clearJMenuItem.setToolTipText("Clears form of all inputs");
        clearJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearJMenuItemActionPerformed(evt);
            }
        });
        quitJMenu.add(clearJMenuItem);

        printJMenuItem.setMnemonic('P');
        printJMenuItem.setText("Print");
        printJMenuItem.setToolTipText("Prints form as GUI");
        printJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printJMenuItemActionPerformed(evt);
            }
        });
        quitJMenu.add(printJMenuItem);

        quitJMenuItem.setMnemonic('Q');
        quitJMenuItem.setText("Quit");
        quitJMenuItem.setToolTipText("Exits the application");
        quitJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitJMenuItemActionPerformed(evt);
            }
        });
        quitJMenu.add(quitJMenuItem);

        quiltJMenuBar.add(quitJMenu);

        helpJMenu.setMnemonic('H');
        helpJMenu.setText("Help");

        aboutJMenuItem.setMnemonic('A');
        aboutJMenuItem.setText("About");
        aboutJMenuItem.setToolTipText("Show About Form");
        aboutJMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutJMenuItemActionPerformed(evt);
            }
        });
        helpJMenu.add(aboutJMenuItem);

        quiltJMenuBar.add(helpJMenu);

        setJMenuBar(quiltJMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(customerInfoJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(titleJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(buttonsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(quiltsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(customerPricingJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(customerInfoJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(quiltsJPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerPricingJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonsJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceJPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               dateJFormattedTextFieldActionPerformed()
 * Description:         Sets date in our text field
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void dateJFormattedTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateJFormattedTextFieldActionPerformed
        setDate();
    }//GEN-LAST:event_dateJFormattedTextFieldActionPerformed

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               exitJMenuItemActionPerformed()
 * Description:         Quit the application by calling the 
 *                      quitJButtonActionPerformed event handler
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void quitJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJMenuItemActionPerformed
       quitJButtonActionPerformed(evt);
    }//GEN-LAST:event_quitJMenuItemActionPerformed
 
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               printJMenuActionPerformed()
 * Description:         Print form as GUI using PrintUtilties helper class
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void printJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printJMenuItemActionPerformed
        PrintUtilities.printComponent(this);
    }//GEN-LAST:event_printJMenuItemActionPerformed
 
    /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               clearJMenutItemActioinPerformed()
 * Description:         Clears our form 
 *
 * Date:                April 25, 2023
 * History              Log Updated from 4/25/2023

 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    private void clearJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJMenuItemActionPerformed
        clearJButtonActionPerformed(evt);
    }//GEN-LAST:event_clearJMenuItemActionPerformed

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               quitJButtonActionPerformed()
 * Description:         Quits the application
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void quitJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitJButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitJButtonActionPerformed

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               clearJButtonctionPerformed()
 * Description:         Values for all inputs are set to 0 or an empty string,
 *                      we then put focus on invoice number.
 *                      MORE TO COM ESOON!!!!
 *
 * History              Log Updated from 4/14/2023
 * Date:                April 14, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 javax.swing.event.ActionEvent
 * @param               evt javax.swing.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void clearJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearJButtonActionPerformed
        invoiceNumberJFormattedTextField.setText("");
        customerJFormattedTextField.setText("");
        quantityHighJSpinner.setValue(0);
        quantityMediumJSpinner.setValue(0);
        quantityLowJSpinner.setValue(0);
        invoiceNumberJFormattedTextField.requestFocus();
        extendedLowJLabel.setText("");
        extendedMediumJLabel.setText("");
        extendedHighJLabel.setText("");
        subTotalPriceJLabel.setText("");
        taxTotalJLabel.setText("");
        totalPriceJLabel.setText("");
    }//GEN-LAST:event_clearJButtonActionPerformed

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               calculateJButtonActionPerformed()
 * Description:         Calcultes Price for quilts for each item, different quilts
 *                      have different price points. This will also include 
 *                      extended price, subtotal,tax, and total.
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void calculateJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateJButtonActionPerformed
        try {
             int invoiceId = validateInvoiceNumber();
             String customerName = validateCustomerName();
             Quilt quilt = setQuiltQuantities();
             int extendedHighPrice = quilt.calculateHighExtendedPrice();
             int extendedMediumPrice = quilt.calculateMediumExtendedPrice();
             int extendedLowPrice = quilt.calculateLowExtendedPrice();
             extendedHighJLabel.setText(String.valueOf(extendedHighPrice));
             extendedMediumJLabel.setText(String.valueOf(extendedMediumPrice));
             extendedLowJLabel.setText(String.valueOf(extendedLowPrice));
             int subTotal = quilt.calculateSubTotal();
             subTotalPriceJLabel.setText(String.valueOf(subTotal));
             double tax = quilt.calculateTax(subTotal);
             taxTotalJLabel.setText(String.format("%.2f", tax));
             double totalPrice = subTotal + tax;
             totalPriceJLabel.setText(String.format("%.2f", totalPrice));
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Must have 4 digits for ID SKU");
                invoiceNumberJFormattedTextField.requestFocus();
                invoiceNumberJFormattedTextField.selectAll();
            } catch (IllegalArgumentException e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                if (e.getMessage().equals("Please enter a valid customer name (only alphabetical characters and spaces are allowed).")) {
                    customerJFormattedTextField.requestFocus();
                    customerJFormattedTextField.selectAll();
                }
            }   
    }//GEN-LAST:event_calculateJButtonActionPerformed
 
 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               validateInvoiceNumber()
 * Description:         validates if the invoice number has 4 digits, if it does
 *                      user gets a return otherwise  exception is thrown.
 *
 * History              Log Updated from 4/25/2023
 * Date:                April 25, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private int validateInvoiceNumber() {
        String idString = invoiceNumberJFormattedTextField.getText();
        int invoiceId = Integer.parseInt(idString);
        if (idString.length() != 4) {
            throw new NumberFormatException();
        }
        return invoiceId;
}

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               validateCustomerName()
 * Description:         validates if the customer name has all characters
 *                      and spaces. if it does
 *                      user gets a return otherwise  exception is thrown.
 *                      Numbers and special characters are not allowed
 *
 * History              Log Updated from 4/25/2023
 * Date:                April 25, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
private String validateCustomerName() {
    String customerName = customerJFormattedTextField.getText().trim();
    if (!customerName.matches("^[a-zA-Z ]+$")) {
        throw new IllegalArgumentException("Please enter a valid customer name (only alphabetical characters and spaces are allowed).");
    }
    return customerName;
}

 /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               setQuiltQuantities()
 * Description:         sets the number that each type of quilt can produce, 
 *                      will throw an exception if 0 quilts are chosen for our 
 *                      calculate button.
 * History              Log Updated from 4/25/2023
 * Date:                April 25, 2023
 * @author              <i>Steven Halla</i>
 * @version             1.0.0
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/

private Quilt setQuiltQuantities() {
    Quilt quilt = new Quilt();
    byte highQuiltNumber = ((Number) quantityHighJSpinner.getValue()).byteValue();
    byte mediumQuiltNumber = ((Number) quantityMediumJSpinner.getValue()).byteValue();
    byte lowQuiltNumber = ((Number) quantityLowJSpinner.getValue()).byteValue();

    if (highQuiltNumber == 0 && mediumQuiltNumber == 0 && lowQuiltNumber == 0) {
        throw new IllegalArgumentException("Please enter at least one quilt quantity.");
    }
    quilt.setHighQuiltNumber((byte) highQuiltNumber);
    quilt.setMediumQuiltNumber((byte) mediumQuiltNumber);
    quilt.setLowQuiltNumber((byte) lowQuiltNumber);
    return quilt;
}
    
/**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               aboutJMenuItemActionPerformed()
 * Description:         Calls our about menu and displays it
 *
 * History              Log Updated from 4/25/2023
 * Date:                April 25, 2023
 * 
 * @see                 java.awt.event.ActionEvent
 * @param               evt java.awt.event.ActionEvent
 * @author              <i>Steven Halla</i>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    private void aboutJMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutJMenuItemActionPerformed
       //show about form
       About myAbout = new About(this, false);
       myAbout.setVisible(true);
    }//GEN-LAST:event_aboutJMenuItemActionPerformed

  
  /**~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 * Method               main()
 * Description:         Calls default constructor to create form to buy quilts
 *                      and display it
 *
 * History              Log Updated from 4/23/2023
 * Date:                April 23, 2023
 * @author              <i>Steven Halla</i>
 *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*/
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuiltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuiltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuiltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuiltGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuiltGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutJMenuItem;
    private javax.swing.JPanel buttonsJPanel;
    private javax.swing.JButton calculateJButton;
    private javax.swing.JButton clearJButton;
    private javax.swing.JMenuItem clearJMenuItem;
    private javax.swing.JPanel customerInfoJPanel;
    private javax.swing.JFormattedTextField customerJFormattedTextField;
    private javax.swing.JLabel customerJLabel;
    private javax.swing.JPanel customerPricingJPanel;
    private javax.swing.JLabel customerTaxJLabel;
    private javax.swing.JFormattedTextField dateJFormattedTextField;
    private javax.swing.JLabel dateJLabel;
    private javax.swing.JPanel exampleJPanel;
    private javax.swing.JLabel extendedHighJLabel;
    private javax.swing.JLabel extendedLowJLabel;
    private javax.swing.JLabel extendedMediumJLabel;
    private javax.swing.JLabel extendedPriceJLabel;
    private javax.swing.JMenu helpJMenu;
    private javax.swing.JLabel highPriceJLabel;
    private javax.swing.JLabel highQuiltJLabel;
    private javax.swing.JLabel invoiceJLabel;
    private javax.swing.JFormattedTextField invoiceNumberJFormattedTextField;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lowPriceJLabel;
    private javax.swing.JLabel lowQuiltJLabel;
    private javax.swing.JLabel mediumPriceJLabel;
    private javax.swing.JLabel mediumQuiltJLabel;
    private javax.swing.JPanel priceJPanel;
    private javax.swing.JMenuItem printJMenuItem;
    private javax.swing.JSpinner quantityHighJSpinner;
    private javax.swing.JSpinner quantityLowJSpinner;
    private javax.swing.JSpinner quantityMediumJSpinner;
    private javax.swing.JLabel quiltAndTaxPriceJLabel;
    private javax.swing.JMenuBar quiltJMenuBar;
    private javax.swing.JLabel quiltPriceJLabel;
    private javax.swing.JLabel quiltQuantityJLabel;
    private javax.swing.JLabel quiltTItleJLabel;
    private javax.swing.JPanel quiltsJPanel;
    private javax.swing.JButton quitJButton;
    private javax.swing.JMenu quitJMenu;
    private javax.swing.JMenuItem quitJMenuItem;
    private javax.swing.JLabel subTotalJLabel;
    private javax.swing.JLabel subTotalPriceJLabel;
    private javax.swing.JLabel taxTotalJLabel;
    private javax.swing.JLabel titleJLabel;
    private javax.swing.JPanel titleJPanel;
    private javax.swing.JLabel totalPriceJLabel;
    // End of variables declaration//GEN-END:variables
}
